export const carModels: Record<string, string[]> = {
  Acura: ['ILX', 'MDX', 'NSX', 'RDX', 'RLX', 'TL', 'TLX', 'TSX', 'ZDX'],
  Alfa_Romeo: ['147', '156', '159', '166', '4C', 'Giulia', 'Giulietta', 'MiTo', 'Stelvio'],
  Aston_Martin: ['DB9', 'DB11', 'DBS', 'Rapide', 'Vantage', 'Virage', 'Vanquish'],
  Audi: ['A1', 'A3', 'A4', 'A5', 'A6', 'A7', 'A8', 'Q2', 'Q3', 'Q5', 'Q7', 'Q8', 'R8', 'RS3', 'RS4', 'RS5', 'RS6', 'RS7', 'S3', 'S4', 'S5', 'S6', 'S7', 'S8', 'TT'],
  BMW: ['1 Series', '2 Series', '3 Series', '4 Series', '5 Series', '6 Series', '7 Series', '8 Series', 'i3', 'i4', 'iX', 'M2', 'M3', 'M4', 'M5', 'M6', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X7', 'Z4'],
  Bentley: ['Bentayga', 'Continental GT', 'Flying Spur', 'Mulsanne'],
  Buick: ['Enclave', 'Encore', 'Envision', 'LaCrosse', 'Regal', 'Verano'],
  Cadillac: ['ATS', 'CT4', 'CT5', 'CT6', 'CTS', 'Escalade', 'SRX', 'XT4', 'XT5', 'XT6', 'XTS'],
  Chevrolet: ['Blazer', 'Camaro', 'Colorado', 'Corvette', 'Cruze', 'Equinox', 'Express', 'Impala', 'Malibu', 'Silverado', 'Sonic', 'Spark', 'Suburban', 'Tahoe', 'Tracker', 'Traverse', 'Trax'],
  Chrysler: ['200', '300', 'Pacifica', 'Town & Country', 'Voyager'],
  Daewoo: ['Espero', 'Kalos', 'Lacetti', 'Lanos', 'Leganza', 'Matiz', 'Nubira'],
  Daihatsu: ['Ayla', 'Feroza', 'Gran Max', 'Rocky', 'Sigra', 'Sirion', 'Terios', 'Xenia'],
  Dodge: ['Challenger', 'Charger', 'Dart', 'Durango', 'Grand Caravan', 'Journey', 'Ram 1500', 'Viper'],
  Eagle: ['Summit', 'Talon', 'Vision'],
  Ferrari: ['296 GTB', '488', '812', 'California', 'F8', 'GTC4Lusso', 'LaFerrari', 'Portofino', 'Roma', 'SF90'],
  Fiat: ['124 Spider', '500', '500L', '500X', 'Bravo', 'Doblo', 'Ducato', 'Freemont', 'Panda', 'Punto', 'Tipo'],
  Fisker: ['Karma', 'Ocean'],
  Ford: ['Bronco', 'EcoSport', 'Edge', 'Escape', 'Expedition', 'Explorer', 'F-150', 'F-250', 'Fiesta', 'Focus', 'Fusion', 'Galaxy', 'Maverick', 'Mondeo', 'Mustang', 'Puma', 'Ranger', 'Territory'],
  Freightliner: ['Cascadia', 'Columbia', 'Coronado', 'M2', 'Sprinter'],
  GMC: ['Acadia', 'Canyon', 'Envoy', 'Jimmy', 'Safari', 'Sierra', 'Sonoma', 'Terrain', 'Yukon'],
  Genesis: ['G70', 'G80', 'G90', 'GV70', 'GV80'],
  Geo: ['Metro', 'Prizm', 'Tracker'],
  Honda: ['Accord', 'BR-V', 'City', 'Civic', 'CR-V', 'CR-Z', 'Freed', 'HR-V', 'Jazz', 'Mobilio', 'Odyssey', 'Passport', 'Pilot', 'Ridgeline', 'WR-V'],
  Hummer: ['H1', 'H2', 'H3', 'EV'],
  Hyundai: ['Accent', 'Avante', 'Creta', 'Elantra', 'Genesis', 'Grand i10', 'i10', 'i20', 'i30', 'Ioniq', 'Ioniq 5', 'Ioniq 6', 'Kona', 'Nexo', 'Palisade', 'Santa Fe', 'Sonata', 'Starex', 'Staria', 'Tucson', 'Veloster'],
  Infinity: ['EX', 'FX', 'G', 'JX', 'M', 'Q50', 'Q60', 'Q70', 'QX50', 'QX56', 'QX60', 'QX70', 'QX80'],
  Isuzu: ['D-Max', 'Elf', 'MU-X', 'Panther', 'Trooper'],
  Jaguar: ['E-Pace', 'F-Pace', 'F-Type', 'I-Pace', 'S-Type', 'X-Type', 'XE', 'XF', 'XJ'],
  Jeep: ['Cherokee', 'Compass', 'Gladiator', 'Grand Cherokee', 'Patriot', 'Renegade', 'Wrangler'],
  Kla: ['Carnival', 'Ceed', 'EV6', 'Forte', 'K5', 'Niro', 'Optima', 'Picanto', 'Rio', 'Seltos', 'Sorento', 'Soul', 'Sportage', 'Stinger', 'Telluride'],
  Lamborghini: ['Aventador', 'Gallardo', 'Huracan', 'Urus'],
  Land_Rover: ['Defender', 'Discovery', 'Discovery Sport', 'Freelander', 'Range Rover', 'Range Rover Evoque', 'Range Rover Sport', 'Range Rover Velar'],
  Lexus: ['CT', 'ES', 'GS', 'GX', 'IS', 'LC', 'LFA', 'LS', 'LX', 'NX', 'RC', 'RX', 'UX'],
  Lincoln: ['Aviator', 'Continental', 'Corsair', 'MKC', 'MKS', 'MKT', 'MKX', 'MKZ', 'Navigator'],
  Lotus: ['Elise', 'Emira', 'Evija', 'Evora', 'Exige'],
  MAZDA: ['2', '3', '5', '6', 'CX-3', 'CX-5', 'CX-8', 'CX-9', 'MX-5', 'MX-30', 'RX-7', 'RX-8'],
  Maserati: ['Ghibli', 'GranTurismo', 'Grecale', 'Levante', 'MC20', 'Quattroporte'],
  Maybach: ['57', '62', 'GLS 600', 'S 450', 'S 560', 'S 580'],
  McLaren: ['570S', '600LT', '620R', '650S', '675LT', '720S', '750S', 'Artura', 'GT', 'P1', 'Senna'],
  Mercedes_Benz: ['A-Class', 'B-Class', 'C-Class', 'CLA', 'CLS', 'E-Class', 'EQA', 'EQB', 'EQC', 'EQE', 'EQS', 'G-Class', 'GLA', 'GLB', 'GLC', 'GLE', 'GLS', 'S-Class', 'SL', 'SLC', 'Sprinter', 'V-Class'],
  Mercury: ['Grand Marquis', 'Mariner', 'Milan', 'Montego', 'Mountaineer', 'Sable'],
  Mini: ['Clubman', 'Convertible', 'Countryman', 'Coupe', 'Hatch', 'Paceman', 'Roadster'],
  Mitsubishi: ['Eclipse Cross', 'Expander', 'Galant', 'L200', 'Lancer', 'Mirage', 'Outlander', 'Pajero', 'Xpander'],
  Nissan: ['370Z', 'Almera', 'Ariya', 'Frontier', 'GT-R', 'Juke', 'Kicks', 'Leaf', 'Livina', 'Magnite', 'March', 'Murano', 'Navara', 'Note', 'Pathfinder', 'Patrol', 'Qashqai', 'Serena', 'Terra', 'Titan', 'X-Trail'],
  Oldsmobile: ['Alero', 'Aurora', 'Bravada', 'Intrigue', 'Silhouette'],
  Panoz: ['Esperante', 'GTR-1'],
  Plymouth: ['Breeze', 'Neon', 'Prowler', 'Voyager'],
  Pontiac: ['Aztek', 'Bonneville', 'Firebird', 'G6', 'Grand Am', 'Grand Prix', 'GTO', 'Montana', 'Solstice', 'Torrent', 'Vibe'],
  Porsche: ['718', '911', 'Boxster', 'Cayenne', 'Cayman', 'Macan', 'Panamera', 'Taycan'],
  Ram: ['1500', '2500', '3500', 'ProMaster'],
  Rolls_Royce: ['Cullinan', 'Dawn', 'Ghost', 'Phantom', 'Silver Shadow', 'Spectre', 'Wraith'],
  Saab: ['9-3', '9-5', '9-7X'],
  Saturn: ['Astra', 'Aura', 'Ion', 'Outlook', 'Sky', 'Vue'],
  Smart: ['EQ Fortwo', 'Forfour', 'Fortwo'],
  Subaru: ['BRZ', 'Forester', 'Impreza', 'Legacy', 'Levorg', 'Outback', 'WRX', 'XV'],
  Susuki: ['Alto', 'Baleno', 'Carry', 'Celerio', 'Ertiga', 'Ignis', 'Jimny', 'Swift', 'SX4', 'Vitara', 'XL7'],
  Tesla: ['Cybertruck', 'Model 3', 'Model S', 'Model X', 'Model Y', 'Roadster'],
  Toyota: ['Agya', 'Alphard', 'Avanza', 'C-HR', 'Calya', 'Camry', 'Corolla', 'Fortuner', 'GR86', 'GR Supra', 'Hiace', 'Hilux', 'Innova', 'Kijang', 'Land Cruiser', 'Prius', 'RAV4', 'Rush', 'Sequoia', 'Sienta', 'Tundra', 'Veloz', 'Vios', 'Voxy', 'Yaris'],
  Volkswagen: ['Amarok', 'Arteon', 'Golf', 'ID.3', 'ID.4', 'Jetta', 'Passat', 'Polo', 'T-Cross', 'T-Roc', 'Tiguan', 'Touareg', 'Touran', 'Up'],
  Volvo: ['C30', 'C40', 'S60', 'S90', 'V40', 'V60', 'V90', 'XC40', 'XC60', 'XC90'],
}